### ISSUE TITLE
Adding this to the project build phase

### ISSUE THREAD

**Issue by ARaqeeb** [Chris2011/minifierbeans#17]
Hi, could you please explain how we can add this to the project build setting? I don't want to be manually minifying the files by choosing the option, mini web content on a folder before building the project.

**Comment by markiewb** [comment]
Why don't you use the onsave-Feature?

https://github.com/jGauravGupta/js-css-minify-compress/blob/c5bb174a873cd8d24876b4550490191a44f4a55b/JS%20CSS%20Minify%20Compress/src/org/netbeans/minify/task/EditorSaveTask.java

**Comment by jGauravGupta** [comment]
This feature is also request by other developers and it will help in mostly case scenario.

But execution of specific action on **project build** will work transparently in case of using existing template (it will also helpful me to serve another functionality in future)

P.S: I have received too many emails for this specific future from last 2 years.

**Comment by Chris2011** [comment]
Still wanted? I would prefer the solution which @markiewb mentioned.

**Comment by Chris2011** [comment]
Minify on save is still available.

**Comment by Chris2011** [comment]
The thing is, building a web project is only possible with a build tool/chain which could be grunt, gulp, whatever. So there is no need for combine this. If you have a build chain with the mentioned tools, you probably have those plugins too in your environment and you don't need them from the IDE.
