### ISSUE TITLE
Plugin not available for Netbeans 8.2

### ISSUE THREAD

**Issue by Antafes** [Chris2011/minifierbeans#28]
Netbeans 8.2 has been released but your awesome plugin isn't available for this version. I've manually installed it with the version for Netbeans 8.1 and it seems to work pretty good, no crashes or other problems so far.
Could you please add a version for Netbeans 8.2 on the plugin portal?

**Comment by meldin** [comment]
Add **http://plugins.netbeans.org/nbpluginportal/updates/8.1/catalog.xml.gz** in plugin setting

**Comment by Bahaatya** [comment]
@meldin What exactly do you mean?

1. How do I install  **js, css, minify Compress** plugin into Netbeans 8.2?

I downloaded the linked compressed file catalog.xml.gz

**1. then what should I do with it?
2. Should I extract it?
3. and where should I place that extracted file?**

**Comment by meldin** [comment]
Go to **Tools**->**plugin** in Netbeans then select **settings** tab click **Add** button then add http://plugins.netbeans.org/nbpluginportal/updates/8.1/catalog.xml.gz in url box

**Comment by Chris2011** [comment]
Please use Apache NetBeans 10.0, for this I built it again. I will probably build it for 9.0 and later for 11.0 too.
