### ISSUE TITLE
Dependencies audit (trying to find them in Maven Central)

### ISSUE THREAD

**Issue by emilianbold** [Chris2011/minifierbeans#41]
Hello Chris,

I'm trying to figure out the Maven coordinates for the binary JAR dependencies you have in release/modules/ext:

* code-minify.jar is com.yahoo.platform.yui:yuicompressor:2.4.7
* gson-2.2.3.jar could be com.google.code.gson:gson:2.2.3 although the binary is different
* html-minify.jar looks like com.googlecode.htmlcompressor:htmlcompressor although not sure which version?
* image-compressor.jar looks like com.github.depsypher:pngtastic although not sure which version?

I see that these JARs have their own dependencies which are not included. For example code-minify needs Rhino: I assume you either don't need it or you are using the Rhino from NetBeans?

**Comment by Chris2011** [comment]
@jGauravGupta hey, can you help here maybe?

**Comment by Chris2011** [comment]
Hey @emilianbold if you are still interested in this, I will move completely to node for JS, CSS (done), HTML, XML, JSON, etc. So I will not need those dependencies anymore. They are old and unmaintained.


Cheers

Chris

**Comment by Chris2011** [comment]
I think we can close this, due to whole refactoring. Just not needed anymore.
