### ISSUE TITLE
Thank you for ES6 compression!

### ISSUE THREAD

**Issue by marcelboere** [Chris2011/minifierbeans#48]
Thank you for making ES6 compression work! I have one question, it seems like the minifierbeans tab page in the Tools|Options menu (tested in Netbeans 10/11) is not being added. Am I doing something wrong? Compressing ES6 works perfectly. Also I'm wondering if an alternative user defineable target path for compressed files is provided in this new version, next to the default path.

**Comment by Chris2011** [comment]
Hey, thx for the feedback :). I moved the minifertab from top-level to second-level under html. I didn't find time to update the screenshots 😎. IMHO it makes more sense to find it there, because it is related to HTML, CSS, JS, etc.

Here it is: 
![image](https://user-images.githubusercontent.com/795658/56344408-99e2c680-61bd-11e9-90dd-c9678789980e.png).

> Also I'm wondering if an alternative user defineable target path for compressed files is provided in this new version, next to the default path.

You mean not putting the files into the same folder of the original file, right? Sure, please make a new file maybe with a proposal, what you think how it could look like 😊


Cheers

Chris

**Comment by marcelboere** [comment]
Thank you Chris, I found the settings tab. what I mean is the following: In the Project Build tab you can select  Create Separate Build folder. First of all it would be nice if a user could change the name of the default _BUILD suffix and maybe define some relative path changes (i.e. ..\) to put the compressed files on a different directory level. Second, I was wondering why the uncompressed source file is being copied into the _BUILD folder. The only way to get your minified sources up to date is to recompress the full folder, because when I select compress in the original folder on a single file (where I am editing my files) by right clicking, it writes the minified file in the same folder and does not update the one in the _BUILD folder. In fact, I'm expecting the minified version being written into the _BUILD folder (which I would like to call _min) and also the original edited file being copied there. Same for only editing the uncompressed file: once you expect a copy in the _BUILD folder you should also update the copy on save. By leaving out the uncompressed file in the _BUILD folder it is more clear which files are current, now (of course depending on selected paths) you get multiple results when searching for a function. The extra uncompressed copy brings unecessary versioning problems. If you only change one file you have to recompress all. Moving the _BUILD (_min) folder to another level could prevent users finding results in compressed and uncompressed files as well. Hope I'm a bit clear here, still very happy with your work! Greetings, Marcel.

**Comment by Chris2011** [comment]
Hey Marcel,

there are two tickets open, both originally created by me: https://github.com/Chris2011/minifierbeans/issues/22 (Change the name of the build folder) and this: https://github.com/Chris2011/minifierbeans/issues/21 (Dev files are inside build folder)

So the first is to customize this folder (changing name, adding relative pathes to it, etc.) This is what you requested. And the second is the problem that you encountered. So again please create a separate ticket, it has nothing to do with this ticket. Maybe you can comment into those tickets or create a separate one, if you think it is a different approach. Thx :)

**Comment by Chris2011** [comment]
FYI I'm aware of the open tickets, but you know prios. My first prio was to remove the old YUICompressor with Google Closure Compiler. Now more and more will go through the other tickets.

**Comment by marcelboere** [comment]
Thank you Chris, sorry I forgot to check the tickets. With making ES6 compress and work as top priority you have helped lots of Netbeans already (The only way to get compressed E6S was to downgrade through Babel and do compress there). I'll check the tickets and visit your page on a regular basis. No issues with Netbeans 11 so far :). Greetings, Marcel.
