### ISSUE TITLE
Cannot install in NB9

### ISSUE THREAD

**Issue by caphill7** [Chris2011/minifierbeans#49]
I hit a snag installing the plugin in NB9 because it complains about the Progress API (>=1.50.1 but only found 1.49.1) and Utility API versions (>= 9.11.1 but only found 9.9.1).

**Comment by Chris2011** [comment]
Hi, thx for the info. Honestly I didn't test it with 9 when I developed it inisde NB 10. I previously developed it in NB 9 and there it worked. Maybe I will need to compile it in NB 9. But if possible, please try it in NB 10 or 11 :)

**Comment by Chris2011** [comment]
Anything new here @caphill7? Could you test it with 10 or 11? I think I will drop 9 and will only support the current version which is 10 for me and stable for all is 11.

**Comment by caphill7** [comment]
Hi, I'm not able to test it with NB10 or 11. I use NB9/JDK11 at work as part of my employer's tool suite and do not have the authority to change/upgrade versions. The reason we use NB9 is because of the lack of sufficient JavaEE support in NB10+.  Even if I was able to successfully test the plugin on NB10 or 11 it wouldn't solve my particular use-case.

**Comment by Chris2011** [comment]
As I understand it right, you need Java EE? But afaik it is not supprted in NB 9. Don't know it yet. So you can't update NetBeans? I need to download NB 9 to compile it there. Will check it later.

**Comment by caphill7** [comment]
For the last few years our development was formerly done in JDK8/NB8. At the end of 2018 when JDK8 went end-of-life and JDK11 was granted LTS status, we had to adopt JDK11 for policy compliance reasons. As you hinted, NB9 does not inherently support JavaEE as JDK9+ removed JavaEE from its core libraries. However, NB9 can still work with JavaEE by installing NB8 EE-related plugins. However, this workaround does not play nicely with NB10+ due to upgraded internal module version numbers similar to the issue I raised with your plugin. Apache has not provided guidance on when, or even if, JavaEE support will be returned to NB in the future as they are solely focused on supporting JavaSE right now.

**Comment by Chris2011** [comment]
As I understand it right, Java EE is now supported with NB 11.0: https://cwiki.apache.org/confluence/display/NETBEANS/Apache+NetBeans+11.0+New+and+Noteworthy maybe I missed smth but it is there. You don't need to switch the SDK, only NetBeans.

If you still don't want this, please give me some time to try it out in NB 9.

**Comment by caphill7** [comment]
Ok, thank you for that, this is new information. I'll forward it upstream, and perhaps we can upgrade to NB11 in the future. Until then, I must continue using the current tool set.

**Comment by Chris2011** [comment]
Will take a look in the next days.

**Comment by Chris2011** [comment]
It should work now. Sry for the late fix. Please test :)
