### ISSUE TITLE
Character string problem in JS

### ISSUE THREAD

**Issue by varadinet** [Chris2011/minifierbeans#50]
Special characters in strings are modified by v2.4.0. A line like
_var a = "\<div\>anything\</div\>";_
is converted to
_var a="\x3cdiv\x3eanything\x3c/div\x3e";_

Please leave character strings unchanged!

**Comment by Chris2011** [comment]
Hey, thx for the report. Will look at it soon :)

**Comment by Chris2011** [comment]
Fixed in 2.5.0
