### ISSUE TITLE
Disable strict mode for JS files

### ISSUE THREAD

**Issue by JayEn84** [Chris2011/minifierbeans#51]
The new plugin version using closure compiler seems to compile in `ECMASCRIPT6_STRICT`, which means that a `'use strict;'` command is prepended to the minified JS files. This command makes my complete JavaScript code not work anymore. (I don't know why though, because the console does not throw any error.)
I think the strict mode should either be disabled, or the user should be enabled to configure the parameters for closure compiler by himself.

**Comment by Chris2011** [comment]
Thx for reporting it. Will have a look at it. Will disable it, at first run. I can add it later via options. If you want, you can make a PR.

**Comment by JayEn84** [comment]
Thank you so much, Chris! I'd love to support you with this project, but I'm a web developer and haven't programmed Java in years. I don't even find the line that would have to be changed, because I guess the `closure-compiler-v20190325.jar` file needs to be re-compiled?! *ducks away*

**Comment by Chris2011** [comment]
I don't think so, I think it will be a flag where I have to set it. I guess, need to check it too, but this is what makes sense to me.

**Comment by Chris2011** [comment]
Hm, unfortunately needs more investigation. Setting to that option doesn't work :/ Will check it.

**Comment by JayEn84** [comment]
That's a pity! After having the awesome idea of opening the .jar files of your project in NetBeans instead of an editor, I was able to find the corresponding lines and thought I'd give it a try once I find the time, but it seems I can't be of any help here. :-/

**Comment by Chris2011** [comment]
I don't know what you were trying exactly but leet us talk in private if you want. Via Slack e.g. :)

**Comment by Chris2011** [comment]
Got it working. I was in the wrong place :D

**Comment by Chris2011** [comment]
Fixed in 2.5.0
