### ISSUE TITLE
Header information cannot be deleted

### ISSUE THREAD

**Issue by JayEn84** [Chris2011/minifierbeans#52]
The plugin allows to save additional header information which will then be added to the minified file. But it is not possible to delete a previously saved text. If the field's content is removed and NetBeans is restarted, the previously saved text will still be there. (Counts for all file types - JS, CSS, HTML, XML, JSON)

(Tested with NetBeans 11.)

**Comment by Chris2011** [comment]
You mean in the options?

**Comment by JayEn84** [comment]
> You mean inside the options?

Yes, sorry.

**Comment by Chris2011** [comment]
So you hit apply and it seems removed after reopening the options, but when you restart NetBeans it is still there?

**Comment by JayEn84** [comment]
Exactly.

**Comment by Chris2011** [comment]
Thy, maybe apply doesn't work. Will check it, but not that soon. Maybe you can help me while checking it too.

**Comment by JayEn84** [comment]
Just found out that the "Apply" button is always disabled - no matter which settings I change in the minifierbeans plugin. However, this is most likely not the cause of this specific problem, because the other settings seem to be saved when clicking "OK" (instead of "Apply").

As a Web Developer, I have experience with HTML forms. In HTML, empty form elements will not be transferred after the submit. Maybe this points in the right direction.

**Comment by Chris2011** [comment]
Hm, good point. Could be.

**Comment by Chris2011** [comment]
Thx for the further investigation.

**Comment by JayEn84** [comment]
I have taken a look at the source code. (Although I don't develop in Java. Thus I have no idea of NetBeans plugin development, so please excuse if the following idea is completely dumb.)
There are five code blocks in `minifierbeans\src\org\netbeans\minify\ui\JSCSSMinifyCompressCustomPanel.java` where the text field inputs of the different tabs of your plugin settings are handled. Here's the one for the JS tab:

```
public void focusLost(FocusEvent fe) {
	String text = headerEditorPaneJS1.getText();
	if (text == null || text.trim().isEmpty()) {
		text = null;
		headerEditorPaneJS1.setText("");
	} else {
		text = text.trim();
	}
	minifyProperty.setHeaderJS(text);
}
```

If the field's content is `null` or empty, your declare `text = null;`. Later, you try to save this with `minifyProperty.setHeaderJS(text);`, but this function expects a string as parameter (not `null`). I guess you have to replace `text = null;` with `text = "";` in case the text field is empty (counts for all five tabs).
I am not able to test this, because I don't know what to do after changing the code. :-)

**Comment by Chris2011** [comment]
Should be fixed now. Thx for the PR.
