### ISSUE TITLE
single row?

### ISSUE THREAD

**Issue by scascalesageinfoes** [Chris2011/minifierbeans#55]
ver  2.5.1:
Netbeans 11

Hello. Now i have multiple rows when minify js. HOw i can render in one single line?

**Comment by Chris2011** [comment]
Hi, please paste your JS file, which you want to minify here: https://pastebin.com/

**Comment by scascalesageinfoes** [comment]
var msgValidEmail = ' debe contener un e-mail valido. ';
var JsCheck = ' Revise la siguiente informaciÃ³n ';
var MustNumber = ' debe contener un nÃºmero ';
var MustNumberBetween = ' debe contener un nÃºmero entre ';
var Jsand = ' y ';
var isReq = ' es obligatorio ';
var PassShould = ' La contraseÃ±a debe tener al menos 6 dÃ­gitos ';
var PassRetype = ' Por favor chequear que contraseÃ±a se ingresada correctamente las dos veces ';
var GetEsDesktop = isMobile() ? false : true;
var showalert = 1;

function redirect(url) { //v4.0
    document.location.href = url;
    return false;
}

function MM_findObj(n, d) { //v4.0
    var p, i, x;
    if (!d)
        d = document;
    if ((p = n.indexOf("?")) > 0 && parent.frames.length) {
        d = parent.frames[n.substring(p + 1)].document;
        n = n.substring(0, p);
    }
    if (!(x = d[n]) && d.all)
        x = d.all[n];
    for (i = 0; !x && i < d.forms.length; i++)
        x = d.forms[i][n];
    for (i = 0; !x && d.layers && i < d.layers.length; i++)
        x = MM_findObj(n, d.layers[i].document);
    if (!x && document.getElementById)
        x = document.getElementById(n);
    return x;
}

Generate two lines

**Comment by Chris2011** [comment]
As I said, use pastebin.com, not in here. Thx.

**Comment by scascalesageinfoes** [comment]
https://pastebin.com/PKSRqPvK

**Comment by Chris2011** [comment]
Thx, will try it out later :)

**Comment by Chris2011** [comment]
This is a feature by the closure compiler. It works as intended. Please read here: https://developers.google.com/closure/compiler/faq#linefeeds


> #### Why are there random line feeds in compiled scripts?
> The Closure Compiler intentionally adds line breaks every 500 characters or so. Firewalls and proxies sometimes corrupt or ignore large JavaScript files with very long lines. Adding line breaks every 500 characters prevents this problem. Removing the line breaks has no effect on a script's semantics. The impact on code size is small, and the Compiler optimizes line break placement so that the code size penalty is even smaller when files are gzipped.
