### ISSUE TITLE
Control file permissions

### ISSUE THREAD

**Issue by HeyConDev** [Chris2011/minifierbeans#56]
Hi guys,
thanks for a great netbeans plugin.

Is there a way to control file permissions of the generated minified files?

with regards from germany
Ariane

**Comment by Chris2011** [comment]
Hi, no. What is the problem?

**Comment by Chris2011** [comment]
Unfortuantely, without having more information, I can't help here. Please reopen if still valid and give detailed information and what your use case or problem is.
