### ISSUE TITLE
netbeans 11.3 compatibility

### ISSUE THREAD

**Issue by stixpunk** [Chris2011/minifierbeans#57]
after upgrading to netbeans 11.3 (jdk14), plugin install will always fail:

`The Plugin Installer found problem timeout of loading MinifierBeans[org.netbeans.minify/2.5.1] while install the following plugins:
MinifierBeans`

have you any idea, where could be problem?

**Comment by Chris2011** [comment]
Hey,

no I didn't try it yet with NB 11.3. Will check it soon. Thx :). Is it possible, that you can change the JDK for your running NetBeans to check whether it is a problem with JDK14 or not? That would be great.

**Comment by stixpunk** [comment]
Ok, it's related to jdk14. I switch to jdk 13.0.1 and installation was complete without errors. After switching back to jdk 14 and try to minify css file, plugin working. So problem is probably only with installation

**Comment by Chris2011** [comment]
It could be, that this is smth related to the unpack200 dependency, which was removed in JDK14. Just guessing: https://github.com/junichi11/netbeans-rainbow-braces/issues/10. And at the Apache NetBeans mailinglist: https://lists.apache.org/thread.html/r9cda0dbe9d390017d87f6a7633b2fe2c84b6d1d107353355518fd06f%40%3Cdev.netbeans.apache.org%3E

As I said, it is just guessing, that this could be related to that. Will check it later. Thx for the info :)

**Comment by Chris2011** [comment]
Yes as I thought, unfortunately it is because of the missing pack200. I use some external dependencies (closure-compiler) and NetBeans tries to call the pack200.exe which is not implemented in JDK14 anymore. I got this exception while installing:

```
java.io.IOException: CreateProcess error=2, Das System kann die angegebene Datei nicht finden
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:483)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:158)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
Caused: java.io.IOException: Cannot run program "C:\Program Files\Java\jdk-14\bin\unpack200.exe" (in directory "C:\Users\Chrl\AppData\Roaming\NetBeans\11.3\modules\ext"): CreateProcess error=2, Das System kann die angegebene Datei nicht finden
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
[catch] at org.netbeans.updater.ModuleUpdater.unpack200(ModuleUpdater.java:567)
	at org.netbeans.updater.ModuleUpdater.unpack(ModuleUpdater.java:465)
	at org.netbeans.updater.ModuleUpdater.run(ModuleUpdater.java:117)
INFO [org.netbeans.updater]: File C:\Users\Chrl\AppData\Roaming\NetBeans\11.3\modules\ext\closure-compiler-v20190325.jar.pack.gz deleted.
INFO [org.netbeans.updater]: Ignore non-readable files 
java.io.FileNotFoundException: C:\Users\Chrl\AppData\Roaming\NetBeans\11.3\modules\ext\closure-compiler-v20190325.jar (Das System kann die angegebene Datei nicht finden)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:212)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:154)
	at org.netbeans.updater.UpdateTracking.getFileCRC(UpdateTracking.java:507)
[catch] at org.netbeans.updater.ModuleUpdater.unpack(ModuleUpdater.java:469)
	at org.netbeans.updater.ModuleUpdater.run(ModuleUpdater.java:117)
WARNING [org.netbeans.updater]: Error: Cannot delete C:\Users\Chrl\AppData\Roaming\NetBeans\11.3\update\download\org-netbeans-minify.nbm
```

Atm I don't know how I can fix this.

**Comment by Chris2011** [comment]
Hi, the problem that @stixpunk mentioned was the JDK 14 problem with the pack200 thing. So it is independent from the version of the Minifierbeans.

The thing with the hidden menu, I moved the menu from TopLevel to the level where it belongs to. So you can find it in the HTML5 options section. I didn't update the screenshots, sry. But you know, it is part of the documentation :D. So please see the changelog and/or the releases: https://github.com/Chris2011/minifierbeans/releases/tag/2.3.0

With 2.3.0 I moved it from TopLevel Category to SubCategory. So in 2.5.1 you will find all options under HTML5 -> Minifierbeans.

**Comment by Chris2011** [comment]
BTW the next version 3.0.0 will have a big update (Adding CSSNano, Using Maven instead of Ant and using a TreeView inside the options) will hopefully fix the problem with JDK14, due to using Maven instead of Ant. But I don't know it, just guessing.

**Comment by arnofly** [comment]
Hi,

Thx for your reply.
Found! OK, I need new eyes :)

Good evening

------ Message d'origine ------
De: "Chrizzly" <notifications@github.com>
À: "Chris2011/minifierbeans" <minifierbeans@noreply.github.com>
Cc : "arnofly" <arnofly@live.fr>; "Comment" <comment@noreply.github.com>
Envoyé : 14/04/2020 20:31:54
Objet : Re: [Chris2011/minifierbeans] netbeans 11.3 compatibility (#57)

**Comment by Chris2011** [comment]
I think we need a new documentation/screenshots ;). If you want and have time please provide new screenshots for that. I would really appreciate it :)

**Comment by arnofly** [comment]
I never have time... but follow the link ;)
https://send.firefox.com/download/b3314b1c7e5bafa0/#xD1Nr0Sf4ZLPlZBmjHWHdQ

See you
Arnaud

------ Message d'origine ------
De: "Chrizzly" <notifications@github.com>
À: "Chris2011/minifierbeans" <minifierbeans@noreply.github.com>
Cc : "arnofly" <arnofly@live.fr>; "Comment" <comment@noreply.github.com>
Envoyé : 14/04/2020 21:38:14
Objet : Re: [Chris2011/minifierbeans] netbeans 11.3 compatibility (#57)

**Comment by Chris2011** [comment]
Great. Thx :)

**Comment by arnofly** [comment]
Your welcome ;)

**Comment by Chris2011** [comment]
So at the end, the problem was with JDK 14 and the missing unpack module. Workaround: Change to a JDK < 14 and install it. I don't know whether the rewrote to maven fixed the problem anyway.
