### ISSUE TITLE
javascript let makes minify fail

### ISSUE THREAD

**Issue by sugenganthos** [Chris2011/minifierbeans#58]
if i define js variable using 'let' instead of 'var', 
js minify is failed (empty result)

note: I'm not using pure js. But a template for php parser. So it is html file contains html, css, php (inside tags) and javascript.

Example js contains php:
`var currentServer = "<?=date('Y-m-d)?>";`

**Comment by Chris2011** [comment]
Hey, which JDK you have, which NetBeans version and which minifierbeans version you use? Does the problem appears just in a PHP file? What about HTML file? What about a plain JS file? Please share a bit more code here. To understand that. Thx :)

**Comment by sugenganthos** [comment]
I'm using JDK10, NB 11.3 Minifier 2.5.1
I have test case: 

footer.html
`	
<footer id="main-footer">
&lt;div class="copyright"&gt;
&lt;p&gt;Using Fugue Icons by </p>
&lt;/div&gt;
&lt;/footer&gt;
<script>

    var a = 123;

    var b = 0;

    for(let i=0; i < 123; i++){

        b++;

    }

&lt;/script&gt;
&lt;/body&gt;
&lt;/html&gt;`

That is failed to minify. If I changed to

`	
<footer id="main-footer">
&lt;div class="copyright"&gt;
&lt;p&gt;Using Fugue Icons by </p>
&lt;/div&gt;
&lt;/footer&gt;
<script>

    var a = 123;

    var b = 0;

    for(var i=0; i < 123; i++){

        b++;

    }

&lt;/script&gt;
&lt;/body&gt;
&lt;/html&gt;`

It can successfully compiled. Clearly `let` makes it failed.
However, 
common.js
`var a = 123;
var b = 0;
for(let i=0; i < 123; i++){
    b++;
}`
It works. Whether it use `let `or `var`. Also it took longer and may have different result.
Pure HTML or HTML with PHP lines makes no difference.

**Comment by sugenganthos** [comment]
Also another failed:
header.html
```html
<html>
    <head>
	<title><?=$title?></title>	
	<link rel="stylesheet" href="<?=base_url('aset/common.css')?>" type="text/css" >
	<script type="text/javascript" src="<?=base_url('aset/zxcvbn.js')?>"></script>
    </head>
```
the 'script' line makes it fail. If I remove the line, or remove PHP template, it works
```html
<html>
    <head>
	<title><?=$title?></title>	
	<link rel="stylesheet" href="<?=base_url('aset/common.css')?>" type="text/css" >
	<script type="text/javascript" src="aset/zxcvbn.js"></script>
    </head>
```
above works.

However, this is less annoying because I can just remove the line before minfying and just add the line on the results

**Comment by Chris2011** [comment]
One little thing here. If you use PHP in a HTML file, you should really rename the file to *.php. It is clear that there is PHP inside. There is no reason why you should use an HTML file with PHP inside. FYI.

If you say it fails, did you get any errors? Smth inside the IDE log or so? If you rename your header.html to header.php is the error still there?

**Comment by Chris2011** [comment]
And more info is needed. What minification did you try? Right click on the HTML file or Minify on the project?

**Comment by Chris2011** [comment]
Ahh now I get it. The problem is, for JS files it uses the new closure compiler, which I implemented. Before, YUICompressor was used, which is deprecated and not developed anymore. However, the problem is that for HTMl files, it doesn't use the closure compier. I can try, maybe it is easy to use closure compiler for embedded JS inside of HTML files or not. Thx for the information :).

**Comment by sugenganthos** [comment]
I do minify on HTML file. 
The IDE just say "errors occured". No more than that. I'm also using your minify plugin on previous version of NB. At first I don't realize the errors until I see the results just blank.

The reason I use template as HTML because I can minify it :) . I cannot use it on php files. 
It is best to have page minified to make page faster because it has smaller size.

Thank's for your response anyway.

**Comment by Chris2011** [comment]
Ok unfortunately it is not easy. Minifierbeans uses HTMLCompressor, which is also old and not maintained anymore. Internally it uses YUICssCompressor and YUIJavaScript compressor. So until, I moved everything to newer versions (using node instead of old, unmaintained java wrappers. So for now as a workaround, you can compress the inline JS in a js file and paste it into the html file.

**Comment by Chris2011** [comment]
> The reason I use template as HTML because I can minify it :) . I cannot use it on php files.
It is best to have page minified to make page faster because it has smaller size.

Ahh I understand. So please create a new ticket to have support for PHP files in Minifierbeans too. This is out of topic here :).

**Comment by sugenganthos** [comment]
> 
> 
> Ok unfortunately it is not easy. Minifierbeans uses HTMLCompressor, which is also old and not maintained anymore. Internally it uses YUICssCompressor and YUIJavaScript compressor. So until, I moved everything to newer versions (using node instead of old, unmaintained java wrappers. So for now as a workaround, you can compress the inline JS in a js file and paste it into the html file.

OK thanks. That is what I usually do. Also I can just use `var` instead of `let` if possible

**Comment by Chris2011** [comment]
Please try the new version 3.2.0. Now it is possible to minify HTML files with ES6+ syntax. I'm using now the npm package html-minifier-terser. PHP Support is still not supported.
