### ISSUE TITLE
Unable to install version 2.3.0 on netbeans 8.2

### ISSUE THREAD

**Issue by douglasmatheus** [Chris2011/minifierbeans#59]
When I try to install the suggested compatible version, it shows the following message

Some plug-ins require the installation of the Progress - Swing API.
The progress API plug-in - Swing was requested in version> = 1.50.1, but only 1.47.1 was found. The following plug-in is affected: JS CSS Minify Compress
Some plug-ins require that the utilities API plug-in be installed.
The Utilities API plug-in was requested at version> = 9.11.1, but only 9.6.1 was found. The following plug-in is affected: JS CSS Minify Compress.

Do you have a solution, or some other compatible version that supports es6?

**Comment by Chris2011** [comment]
Unfortunately no. 2.3.0 should be compatible with 8.2, yes but it still has no ES6 support. This comes with 2.4.0. Up this version I switched to Google Closure Compiler. So I suggest to use the latest NetBeans which is still 11.3 (12.0 is coming but still in beta) and JDK <14 and Minifierbeans 2.5.1. 8.2 is not supported anymore from my side.

I still have 8.2 and I will try to install version 2.3.0 to test it.

**Comment by Chris2011** [comment]
So I guess it should be possible for you to switch to 11.3 and try Minifierbeans 2.5.1

**Comment by douglasmatheus** [comment]
I followed your recommendation and I'm using version 11 of netbeans. I had initial difficulties to make my project work but apparently it is now working ... however, now when I try to install the minifier it cancels the installation and disappears from the central plugins, and in the netbeans notifications it shows the following error:

Cannot run program "C:\Program Files (x86)\Java\jdk-14\bin\unpack200.exe" (in directory "C:\User\prog03\AppData\Roaming\NetBeans\11.0\modules\ext"): CreateProcess error=2, The system cannot find the file specified

Do you have any idea what it might be?

Thank you for your help.

**Comment by douglasmatheus** [comment]
I tried to use netbeans 9 initially and everything went well with the installation, but when minifying the js files are empty. It happens only with js files, the rest html, css minify right

**Comment by Chris2011** [comment]
You should check my comment again :)

> So I suggest to use the latest NetBeans which is still 11.3 (12.0 is coming but still in beta) and JDK <14 and Minifierbeans 2.5.1

and you should have checked the ticket system to find this #57 . You can't install it with JDK 14, because of the missing pack200. So please use NetBeans 11.3, Minifierbeans 2.5.1 and JDK < 14 which could be 9 - 13.

**Comment by Chris2011** [comment]
> I tried to use netbeans 9 initially and everything went well with the installation, but when minifying the js files are empty. It happens only with js files, the rest html, css minify right

Which version of Minifierbeans do you use? And what is the sample js code, which is not working? Please don't post it here, make a pastebin or gisthub for that and add the link to here.

**Comment by douglasmatheus** [comment]
> 
> 
> You should check my comment again :)
> 
> > So I suggest to use the latest NetBeans which is still 11.3 (12.0 is coming but still in beta) and JDK <14 and Minifierbeans 2.5.1
> 
> and you should have checked the ticket system to find this #57 . You can't install it with JDK 14, because of the missing pack200. So please use NetBeans 11.3, Minifierbeans 2.5.1 and JDK < 14 which could be 9 - 13.

You're right, I didn't notice this detail, I changed the version and the installation worked, thank you very much for your help.

**Comment by douglasmatheus** [comment]
> 
> 
> > I tried to use netbeans 9 initially and everything went well with the installation, but when minifying the js files are empty. It happens only with js files, the rest html, css minify right
> 
> Which version of Minifierbeans do you use? And what is the sample js code, which is not working? Please don't post it here, make a pastebin or gisthub for that and add the link to here.

You're right, I didn't notice this detail, I changed the version and the installation worked, thank you very much for your help.

When it comes to creating the blank file, from what I understand it is because of the comments. Is it supposed to be like that? or have any settings I need to make to ignore comments?

**Comment by Chris2011** [comment]
Comments will be removed afaik. There is no option atm to leave them. If you want that feature, please  create a new ticket for that :)

**Comment by douglasmatheus** [comment]
I didn't express myself properly, I don't want to remove the comments, what happens is that when minifying, the minified file is empty because of the comments inside the code. Removing the comments makes the minification right.

It gets complicated to have to remove comments every time you minify.

**Comment by Chris2011** [comment]
Then please create a new ticket and maybe it will happen with version 3.0.0. Just to track it down, that you want this feature :)

**Comment by douglasmatheus** [comment]
I managed to solve it, the problem was in the words that contained characters like "ã, á, ç..."

This created blank file.

I removed these characters and it worked, now I am also using the latest version of the IDE.

Thank you very much for your patience and help, hug.

**Comment by Chris2011** [comment]
Great to hear. Have fun and you are welcome :)
