### ISSUE TITLE
Issue with single line comments

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Chris2011/minifierbeans#6]
```
What steps will reproduce the problem?
1. CSS with // Comments
2. Right Click and Minimize CSS
3. Output has anything after comment commented out

What is the expected output? What do you see instead?
Expected to remove comments and leave only minimized code.
Comments are left and comment out remaining code.

What version of the product are you using? On what operating system?
 2.0 in Netbeans 8.0 on Windows 8.1

Please provide any additional information below.
I know I could simply use /* Comment */ but my CSS is heavily commented and it 
could be more efficient if it removed comments completely 

```

Original issue reported on code.google.com by `mcgee.w...@gmail.com` on 11 Aug 2014 at 5:04

**Comment by Chris2011** [comment]
As mentioned, css doesn't have single line comment. It is not a correct syntax. Doesn't matter whether the IDE shows it correct as a comment. Just use a linter for this example `// Test body {color:#fff;}` http://csslint.net/ and you will see, that this is wrong.

**Comment by Chris2011** [comment]
As I said, please use supported CSS multi line comments /* ... */ but as a workaround you can use `// blaaa {}` so you need this brackets at the end. But with no guarantee what will break then. It is better to always use the correct syntax.
