### ISSUE TITLE
Plugin not available for Netbeans 11.3

### ISSUE THREAD

**Issue by arie051267** [Chris2011/minifierbeans#68]
Hello,

If I go in Netbeans 11.3 to Tools --> Plugins I can't find MinifierBeans, any idea what I am doing wrong?

**Comment by Chris2011** [comment]
Hi, I need some more info. Which system do you use, which version of Minifierbeans do you tried to install etc. Which operating system. Steps to reproduce. Everything what you did, what I can do to reproduce the problem :).

**Comment by arie051267** [comment]
sorry, my bad .......... :-(

I saw I had installed it a long time ago but I couldn't find it under Installed or Available plugins.

I saw under Installed plugins "User Installed plugins", at the bottom of the explanation I saw: 

_Modules installed: Color Codes Preview, JSHint, PHP Enhancements, **MinifierBeans**, NetBeans CapsLock Notifier, The nb-javac Java editing support library_

So I alreafy had installed it .......... ;-)

**Comment by Chris2011** [comment]
You can check the checkbox to expand all "User installed plugins" and then you can search for minifierbeans and see which version you have.

**Comment by arie051267** [comment]
Tnx for the quick reply, I have 2.5.1 installed

**Comment by Chris2011** [comment]
Try the latest one :).

**Comment by Chris2011** [comment]
See the changelog before for the changes.

**Comment by arie051267** [comment]
I try to update it but I can't see any options for that?

So I delete 2.5.1, restart NetBeans en open Tools --> Plugins

I can see Minifier in the Available section but still it is 2.5.1

I see in the settings tab that the update URL is http://updates.netbeans.org/netbeans/updates/8.2/uc/final/distribution/catalog.xml.gz, 

Try to make this \http://updates.netbeans.org/netbeans/updates/11.3/uc/final/distribution/catalog.xml.gz but that's not the correct URL.

Any idea how to get the latest version into NetBeans?

**Comment by Chris2011** [comment]
It is not in the plugin portal/center you need to download it from here. Go to releases: https://github.com/Chris2011/minifierbeans/releases. I didn't do the upload process to maven central etc. You will only find my plugins released here. Later I will create my own plugin center with all of my plugins and a update URL but maybe next year :)

**Comment by arie051267** [comment]
Tnx, I just updated to 3.2.0
