### ISSUE TITLE
no .nbm file 

### ISSUE THREAD

**Issue by Higestromm** [Chris2011/minifierbeans#81]
Hi,

I didn't see any nbm file to include the plugin into netbean.

Also the url : http://plugins.netbeans.org/plugin/49666/minifierbeans didn't work anymore.

How to install the plugin ?

Thank you :)

**Comment by Chris2011** [comment]
Please have a look at the releases section here on GitHub :)

**Comment by Higestromm** [comment]
Ohhh didn't see that link :/

Thank you :)
