### ISSUE TITLE
Netbeans 12.4 and OpenJ9 9-0.26.0 and minifierbeans 3.3.1

### ISSUE THREAD

**Issue by JuergenLaas** [Chris2011/minifierbeans#84]
Hello,

i have two mashines with Netbeans 12.4 and OpenJ9 9-0.26.0 one the first machine this Plugin works fine.
But on second pc i get follow error in Terminal. If i install minifierbeans 3.3.1 and try to minify CSS-File.

`"C:\Users\Juergen/.netbeans/minifierbeans/custom-packages/postcss.cmd" "--config" "C:\Users\Juergen/.netbeans/minifierbeans/custom-packages" "C:/Users/Juergen/Documents/NetBeansProjects/Bewertungen.10-x.eu/css/style.css" "-o" "C:/Users/Juergen/Documents/NetBeansProjects/Bewertungen.10-x.eu/css/style.min.css"
Der Befehl ""node"" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Done.
`

Product Version: Apache NetBeans IDE 12.4
Java: 16.0.1; Eclipse OpenJ9 VM openj9-0.26.0
Runtime: OpenJDK Runtime Environment 16.0.1+9
System: Windows 10 version 10.0 running on amd64; Cp1252; de_DE (nb)

**Comment by Chris2011** [comment]
Minifierbeans uses node. All those packages are called internall with node. So it seems that you don't have node installed. It says in the error message: `Der Befehl ""node"" ist entweder falsch geschrieben oder konnte nicht gefunden werden`. So first check whether you have node installed and second, go to options -> html5 -> nodejs and set the executable to the path where you have node installed.

**Comment by Chris2011** [comment]
I guess it is as I said, please let me know.
