### ISSUE TITLE
The degree of compression for CSS

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Chris2011/minifierbeans#9]
```
Could use some additional settings options for compression, for example, to 
kompresownay css file was not a single line, but each type elemnt class as a 
new line.


```

Original issue reported on code.google.com by `lukasz.p...@gmail.com` on 21 Apr 2015 at 9:12

**Comment by Chris2011** [comment]
I can add more settings but I don't know whether this specific case is possible for css nano. I know there is a the possibility to remove just the spaces, nothing more and let it readable.

**Comment by Chris2011** [comment]
So I will close this ticket in case of inactivity. I use CSSNano now and if anyone knows what was meant with the issue creator, we can create a new ticket with more information.
