### ISSUE TITLE
[BUG] Minifier doesn't work with non-latin path

### ISSUE THREAD

**Issue by Ilya-Zhulin** [Chris2011/minifierbeans#90]
**Search first**
Please make sure, that your issue is not covered by any other ticket. Please search first before you create a ticket.

- Yes, I'm sure.

**Describe the bug**
Error of minification if project path contains non latin simpbols - russian in my case (Документы).

**To Reproduce**
1. Go to on your PC
2. Click on NetBeans icon
3. Start new project
4. Create new project in the path with non-latin folder name
3. Create JavaScript file
4. Fill it by some code
5. Save this file
6. Try to minify it.
7. See error

**Expected behavior**
I expect, that plug-in works with all path and file will be minified. It works with Latin path.

**Screenshots**
![image](https://user-images.githubusercontent.com/4967754/134828800-4f952143-8488-480a-9811-8079c0df85c4.png)

**Environment (please complete the following information):**
 - OS: Windows 10 the last update
 - NetBeans version: 12.5
 - JDK version: 16

**Additional context**
Now I use Netbeans 12.5 and minifier 3.4. You can copy this word **Документы** to call your folder to replay the problem. This word means **Documents**.

**Comment by Chris2011** [comment]
Hey @Ilya-Zhulin sry but I didn't created the issue template w/o any reason. So why don't you follow the template. Next time I will close the ticket immediately. So as I need to GUESS, you minified one file, right?

Please next time, read the template, go step by step and add every little information that needs to identiy the bug. Thx.

**Comment by Chris2011** [comment]
Also a title is missing.

**Comment by Ilya-Zhulin** [comment]
I described all needed info. I felt your template, now you have also info about my PC.

**Comment by Chris2011** [comment]
Will have a look soon. Thx for reporting :)

**Comment by Chris2011** [comment]
@Ilya-Zhulin please see the last comment: https://github.com/google/closure-compiler/issues/3784#issuecomment-1011453062

**Comment by Ilya-Zhulin** [comment]
Hey! Of course it is not common situation.. I just found it and report to dev. Thanks that you tried to solve it. It's not a big problem, I transferred my files time ago to latin path and now it works good. Thank you.

**Comment by Chris2011** [comment]
Great you for your understanding :)
