### ISSUE TITLE
Can plugin be installed on Netbeans 14?

### ISSUE THREAD

**Issue by jshster** [Chris2011/minifierbeans#96]
Hey guys,
I can't for the life of me work out how to install the plugin in netbeans 14.  Previously I've downloaded a nbm file.   I tried pointing NB14 at the jar files but it only picks up the gson-2.2.3.jar file.  Apparently the other files aren't installable.

Any help would be appreciated.  

I've relied on this plugin for so long I dread the thought of some web based alternative where I have to copy/paste each file individually.

Cheers

**Comment by Chris2011** [comment]
Hey @jshster please use the discussion section for getting help, this is neither a feature request nor a bug. First I need more information from you. What is your operating system, which JDK do you use and which version of minifierbeans did you try?
